name = "Thefoxgang"
license = "MIT"
licenselink = "https://github.com/tevert/hugo-tevert.github.io/blob/master/themes/thefoxgang/LICENSE.md"
description = "A custom theme built based on the original styling for thefoxgang.com"
homepage = "https://www.thefoxgang.com/"
tags = []
features = []
min_version = "0.0.1"

[author]
  name = "Tyler Evert"
  homepage = "https://www.thefoxgang.com/"
